name: Deploy Supabase Migrations

on:
  push:
    branches:
      - main
    paths:
      - 'server/supabase/migrations/**'

jobs:
  deploy-migrations:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Run Migrations
        run: npx supabase migration up --project-ref $PROJECT_ID
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
