name: Deploy Supabase Migrations

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'server/supabase/migrations/**'
      - '.github/workflows/supabase.yml'

jobs:
  deploy-migrations:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Run Migrations
        run: |
          npx supabase migration up --db-url "postgresql://postgres:${SUPABASE_DB_PASSWORD}@${SUPABASE_POOLER_HOST}:5432/postgres?sslmode=require"
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_POOLER_HOST: ${{ secrets.SUPABASE_POOLER_HOST }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
